package com.company;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.text.SimpleDateFormat;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignUpArifTest {

    static final String username = "arif";
    static final String password = "arif";
    static final String newName = "marif";
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","E:\\Document\\vvpl\\chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void signUpError() {
        driver.get("https://google-gruyere.appspot.com/606173267513807308367751952985584048412/");
        driver.manage().window().setSize(new Dimension(1024, 553));
        driver.findElement(By.linkText("Sign up")).click();
        driver.findElement(By.name("uid")).click();
        driver.findElement(By.name("uid")).sendKeys("arif");
        driver.findElement(By.name("pw")).sendKeys("arif");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".message")).getText(), is("Account created."));//test failed karna seharusnya message yang diharapkan adalah "User already exst" karena sudah akun tersebut sudah didaftarkan
    }
    @Test
    public void signUpBerhasil() {
        driver.get("https://google-gruyere.appspot.com/606173267513807308367751952985584048412/");
        driver.manage().window().setSize(new Dimension(1024, 553));
        driver.findElement(By.linkText("Sign up")).click();
        driver.findElement(By.name("uid")).click();
        driver.findElement(By.name("uid")).sendKeys("arif");
        driver.findElement(By.name("pw")).sendKeys("arif");
        driver.findElement(By.cssSelector("tr:nth-child(4) input")).click();
        assertThat(driver.findElement(By.cssSelector(".message")).getText(), is("User already exists."));
    }
    @Test
    public void loginGagal(){
        driver.get("https://google-gruyere.appspot.com/606173267513807308367751952985584048412/");
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.name("uid")).sendKeys(username);
        driver.findElement(By.name("pw")).sendKeys("passwordSalah");
        driver.findElement(By.xpath("/html/body/div[3]/form/table/tbody/tr[3]/td[2]/input")).click();
        assertThat(driver.findElement(By.cssSelector(".message")).getText(), is("Invalid user name or password."));
    }
    @Test
    public void loginBerhasil(){
        driver.get("https://google-gruyere.appspot.com/606173267513807308367751952985584048412/");
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.name("uid")).sendKeys(username);
        driver.findElement(By.name("pw")).sendKeys(password);
        driver.findElement(By.xpath("/html/body/div[3]/form/table/tbody/tr[3]/td[2]/input")).click();
        assertThat(driver.findElement(By.xpath("//*[@id=\"menu-right\"]/a[2]")).getText(), is("Sign out"));//mengecek dengan cara melihat apakah ada tombol sign out, karena habis login ada log out
    }
    @Test
    public void membuatSnippet(){
        driver.get("https://google-gruyere.appspot.com/606173267513807308367751952985584048412/");
        driver.findElement(By.linkText("Sign in")).click();
        driver.findElement(By.name("uid")).sendKeys(username);
        driver.findElement(By.name("pw")).sendKeys(password);
        driver.findElement(By.xpath("/html/body/div[3]/form/table/tbody/tr[3]/td[2]/input")).click();
        driver.findElement(By.linkText("New Snippet")).click();
        Date date = new Date();
        SimpleDateFormat format = new SimpleDateFormat("dd-MM-yyyy HH:mm:ss");
        driver.findElement(By.name("snippet")).sendKeys("Snippet dikirim pada: "+format.format(date));
        driver.findElement(By.xpath("/html/body/div[2]/div/form/table/tbody/tr/td[2]/input")).click();
    }
}

